destinations = [
    {'name': 'プノンペン', 'country': 'カンボジア', 'distance': 0, 'image': '01_phnom_penh.png', 'message': '独立記念塔の周辺は夜まで屋台がにぎわう。トゥールスレン収容所跡ではカンボジア現代史の闇に触れられる。'},
    {'name': 'タケオ', 'country': 'カンボジア', 'distance': 100, 'image': '02_takeo.png', 'message': '古代の遺跡が点在するタケオは「カンボジア文明の発祥地」とも呼ばれる。レンガ造りの祠堂が村の中にひっそり残る。'},
    {'name': 'カンポット', 'country': 'カンボジア', 'distance': 250, 'image': '03_kampot.png', 'message': '世界的に有名なカンポットペッパーの産地。旧フランス統治時代の建物が街角に残る。'},
    {'name': 'ハットレック', 'country': 'カンボジア', 'distance': 400, 'image': '04_hat_lek.png', 'message': '国境の街ハットレックでは、早朝から露店が並び、カンボジアとタイの文化が交錯する。'},
    {'name': 'バンコク', 'country': 'タイ', 'distance': 700, 'image': '05_bangkok.png', 'message': 'チャオプラヤ川を渡る路地裏フェリーに乗ると、華やかな都市の別の顔が見える。タラート・ノイ地区は地元のアート拠点に。'},
    {'name': 'ヤンゴン', 'country': 'ミャンマー', 'distance': 1000, 'image': '06_yangon.png', 'message': 'シュエダゴン・パゴダだけでなく、コロニアル建築が残る中心街も歩いて楽しい。電車環状線ではローカルな日常が見える。'},
    {'name': 'ダッカ', 'country': 'バングラデシュ', 'distance': 1500, 'image': '07_dhaka.png', 'message': '混沌と活気が交差する旧市街では、人力リキシャが今も主役。モスクとバザールが入り混じる街の匂いは強烈。'},
    {'name': 'コルカタ', 'country': 'インド', 'distance': 1800, 'image': '08_kolkata.png', 'message': 'ホーラーブリッジを見下ろす花市場は早朝が見どころ。タゴールゆかりのカフェで詩とチャイに浸れる。'},
    {'name': 'ラホール', 'country': 'パキスタン', 'distance': 2300, 'image': '09_lahore.png', 'message': '旧市街の迷路のようなバザールには、絨毯と香辛料の香りが満ちている。国境セレモニーも名物。'},
    {'name': 'テヘラン', 'country': 'イラン', 'distance': 3300, 'image': '10_tehran.png', 'message': '地下鉄で巡るバザール、宮殿、美術館。イマーム広場近くの書店街には詩と哲学の本が並ぶ。'},
    {'name': 'バグダッド', 'country': 'イラク', 'distance': 3900, 'image': '11_baghdad.png', 'message': '戦禍を越えて復活した書店通り「ムタナビ・ストリート」には、知の都の誇りが残る。'},
    {'name': 'ベイルート', 'country': 'レバノン', 'distance': 4900, 'image': '12_beirut.png', 'message': '中東のパリとも呼ばれた街。戦禍の爪痕とモダンなカフェ文化が不思議に同居している。'},
    {'name': 'カイロ', 'country': 'エジプト', 'distance': 5100, 'image': '13_cairo.png', 'message': 'ピラミッドの裏側はラクダ使いと猫のたまり場。ハンハリーリ市場の迷路では値切りが文化。'},
    {'name': 'アテネ', 'country': 'ギリシャ', 'distance': 6600, 'image': '14_athens.png', 'message': '夜のアクロポリスは遠くから眺めると神秘的。タベルナで聴くブズーキの音色が郷愁を誘う。'},
    {'name': 'ティラナ', 'country': 'アルバニア', 'distance': 7000, 'image': '15_tirana.png', 'message': '共産主義時代の防空壕をアートスペースにした「バンカート」は一見の価値あり。'},
    {'name': 'スコピエ', 'country': 'マケドニア', 'distance': 7300, 'image': '16_skopje.png', 'message': '巨大なアレクサンダー像と不釣り合いなモダン建築が混在するカオス都市。'},
    {'name': 'ベオグラード', 'country': 'セルビア', 'distance': 7800, 'image': '17_belgrade.png', 'message': 'サヴァ川沿いの船上クラブは地元の若者に人気。要塞跡からの夕焼けは一見の価値あり。'},
    {'name': 'ブダペスト', 'country': 'ハンガリー', 'distance': 8100, 'image': '18_budapest.png', 'message': '廃墟を改装した“ルインバー”はこの街独自の文化。セーチェーニ温泉では地元民がチェスに興じている。'},
    {'name': 'ウィーン', 'country': 'オーストリア', 'distance': 8350, 'image': '19_vienna.png', 'message': 'モーツァルト像の裏手にある静かな小径には、カフェと古本屋が隠れている。'},
    {'name': 'パリ', 'country': 'フランス', 'distance': 9350, 'image': '20_paris.png', 'message': 'カルチエ・ラタンの裏通りでは詩人たちの香りがまだ残る。モンマルトルでは絵描きが客引きをしている。'},
    {'name': 'ブリュッセル', 'country': 'ベルギー', 'distance': 9650, 'image': '21_brussels.png', 'message': 'チョコの名店が並ぶ一方で、タンタン博物館のようなポップカルチャーの発信地でもある。'},
    {'name': 'アムステルダム', 'country': 'オランダ', 'distance': 10050, 'image': '22_amsterdam.png', 'message': '自転車で迷い込む運河沿いの古書店街。アートと自由が空気のように漂っている。'},
    {'name': 'ハンブルク', 'country': 'ドイツ', 'distance': 10450, 'image': '23_hamburg.png', 'message': '倉庫街シュパイヒャーシュタットとミニチュアワンダーランドは鉄道ファン必見。'},
    {'name': 'ワルシャワ', 'country': 'ポーランド', 'distance': 10950, 'image': '24_warsaw.png', 'message': '旧市街の石畳に残る戦争の爪痕。ショパンゆかりの場所も静かにたたずんでいる。'},
    {'name': 'ヘルシンキ', 'country': 'フィンランド', 'distance': 11850, 'image': '25_helsinki.png', 'message': 'デザイン博物館とサウナが共存する街。港に浮かぶサウナ船は地元民の憩いの場。'},
]